[package]
name = "simplefileshare"
version = "0.1.0"
edition = "2021"
authors = ["Hugefiver", "Anthony Hoo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.10", features = ["macros", "multipart", "ws", "headers", "http2"] }
clap = { version = "4.1.8", features = ["derive"] }
num = "0.4.0"
rand = "0.8.5"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive", "serde_derive"] }
serde_json = "1.0.94"
sqlx = { version = "0.6.2", features = ["sqlite", "uuid", "macros", "chrono", "offline", "runtime-tokio-rustls"] }
tokio = {version = "1.26.0", features = ["full"]}
tower = { version = "0.4.13", features = ["full", "tokio"] }
xxhash-rust = { version = "0.8.6", features = ["const_xxh3", "xxh3"] }
