name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: clippy
    
    - name: Cargo check
      run: cargo check -V
      
    - name: Run tests
      run: cargo test -V
      
    - name: Clippy
      run: cargo clippy --fix
