name: on-push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: clippy
      
    - name: Clippy
      run: cargo clippy --fix
      
    - name: Run tests
      run: cargo test -v
      
